name: Remove old artifacts

on:
  schedule:
    - cron: "0 0 * * 1"
jobs:
  remove-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Remove old artifacts
        uses: actions/github/artifact-remove-action@v1
        with:
          older-than: 90 days
